
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "email": "caosonhai1410@gmail.com",
    "password": "Password123@"
}
###
POST http://localhost:3030/api/register
Content-Type: application/json

{
    "email": "caosonhai1410002@gmail.com",
    "password": "Password123@",
    "rePassword":"Password123@"
}

###
POST   http://localhost:3030/api/auth/logout

###
POST  http://localhost:3030/api/pay

###
POST  http://localhost:3030/api/carts-products/add-to-cart
Content-Type: application/json

{
    "id":123,
    "quantity":2,
    "currentPrice":34 
}
###
POST http://localhost:3030/api/v1/products/6538941ada3cfdb75e682023/color
Content-Type: application/json

{
    "colorName":"#ffff",
    "productID":"6538941ada3cfdb75e682023"
}
###
GET http://localhost:3030/api/v1/products/6538941ada3cfdb75e682023/color
Content-Type: application/json

{
    "productID":"6538941ada3cfdb75e682023"
}