
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "email": "caosonhai@gmail.com",
    "password": "Password123@"
}
###
POST http://localhost:3030/api/register
Content-Type: application/json

{
    "email": "caosonhai1410002@gmail.com",
    "password": "Password123@",
    "rePassword":"Password123@"
}

###
GET  http://localhost:3030/api/carts